// Vue/src/components/NotesTextAreaComponent.vue
<template>
  <DxTextArea
    :value="cellInfo.value"
    :auto-resize-enabled="true"
    :element-attr="{ class: 'custom-textarea-class' }"
    @initialized="onTextAreaInitialized"
    @value-changed="onValueChanged"
    @input="onTextAreaInput"
  />
</template>

<script setup lang="ts">
import { type DxDataGridTypes } from 'devextreme-vue/data-grid';
import type { DxTextAreaTypes } from 'devextreme-vue/text-area';
import DxTextArea from 'devextreme-vue/text-area';

type TextAreaElement = HTMLElement & {
  prevClientHeight?: number;
};

const { cellInfo } = defineProps<{
  cellInfo: DxDataGridTypes.ColumnEditCellTemplateData;
}>();

const onTextAreaInitialized = (e: DxTextAreaTypes.InitializedEvent) => {
  e.component?.registerKeyHandler('enter', (event: KeyboardEvent) => {
    if (!event.ctrlKey && !event.shiftKey) {
      event.stopPropagation();
    }
  });
};

const onTextAreaInput = (e: DxTextAreaTypes.InputEvent) => {
  const el = e.element as TextAreaElement;
  if (!el) return;

  if (el.prevClientHeight !== el.clientHeight) {
    cellInfo.component?.updateDimensions();
  }

  el.prevClientHeight = el.clientHeight;
};

const onValueChanged = (e: DxTextAreaTypes.ValueChangedEvent) => {
  cellInfo.setValue(e.value);
};
</script>

// React/src/NotesTextAreaComponent.tsx
import { useCallback } from 'react';
import type { DataGridTypes } from 'devextreme-react/data-grid';
import type { TextAreaTypes } from 'devextreme-react/text-area';
import TextArea from 'devextreme-react/text-area';

type TextAreaElement = HTMLElement & {
  prevClientHeight?: number;
};

const textAreaElementAttr = {
  class: 'custom-textarea-class',
};

function NotesTextAreaComponent({ data }: { data: DataGridTypes.ColumnEditCellTemplateData }) {
  const handleValueChanged = useCallback(
    (e: TextAreaTypes.ValueChangedEvent) => {
      data.setValue(e.value);
    },
    [data.setValue],
  );

  const handleNotesInput = useCallback((args: TextAreaTypes.InputEvent) => {
    const el = args.element as TextAreaElement;

    if (el.prevClientHeight !== el.clientHeight) {
      data.component.updateDimensions();
    }

    el.prevClientHeight = el.clientHeight;
  }, [data.component]);

  const handleOnInitialized = useCallback((e: TextAreaTypes.InitializedEvent) => {
    e.component?.registerKeyHandler('enter', (event: KeyboardEvent) => {
      if (!event.ctrlKey && !event.shiftKey) {
        event.stopPropagation();
      }
    });
  }, []);

  return (
    <TextArea
      defaultValue={data.value}
      onValueChanged={handleValueChanged}
      elementAttr={textAreaElementAttr}
      autoResizeEnabled={true}
      onInput={handleNotesInput}
      onInitialized={handleOnInitialized}
    />
  );
}

export default NotesTextAreaComponent;
